### PR TITLE
Issue #61: Drupal 10 compatibility

### PR DESCRIPTION
**Pull request by albeortev**
Package constraints have been updated to support Drupal 10 compatibility.

### CODE REVIEW

**Comment by albeortev** [comment]
Pending review if new versions of the packages do not break functionality.

**Comment by alinabasarabeanu** [comment]
Hi 
Can we have those changes merged into a new stable release? 
We moved to D10 and this plugin is behind and unusable

**Comment by albeortev** [comment]
Necessary adjustments have been completed.

The changes are stable and **ready to be merged** into the main branch.

Note that as of Drupal 10, _CKEditor_ is deprecated by default and _CKEditor5_ is its replacement so this Issue goes hand in hand with #64 and is also ready to merge.

Drupal 10 compatibility - Issue #61 -> PR https://github.com/nuvoleweb/drupal-behat/pull/62 :heavy_check_mark: 
CKEditor5 step adaptation - Issue #64 -> PR https://github.com/nuvoleweb/drupal-behat/pull/66 :heavy_check_mark:

**Comment by Eduardo-Morales-Alberti** [comment]
+1 applied on our projects for Drupal 10

**Comment by bircher** [comment]
Thanks for your contribution!

**Pull request merged**
